### ISSUE TITLE
Implement 1.17 ! (not construc info...)

### ISSUE THREAD

**Issue by ShuNeko** [HyperSMP/EggHuntPlugin#9]
Your project is an very cool smp mécanique but the 1.17 - 1.17.1 versions is not support by the plugin :/ Please add this in the future !

**Comment by J0hnL0cke** [comment]
Added support for Minecraft versions 1.17-1.20.1 in [EggHunt v1.1.1](https://github.com/HyperSMP/EggHuntPlugin/releases/tag/v1.1.1)
